```{r, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(tidyverse)
library(here)
library(class)
```

# Variable Description Table in 3. Data section

According to documents provided by the client, the data contains the following variables in Table 1:
```{r echo=FALSE, message=FALSE}
# Create a sample data frame
data <- data.frame(
  Variable = c("time", "posX", "posY", "orientation", "mac", "signal", "rawTime", "angle"),
  Description = c("Time of Observation", "X coordinate inside building", "Y coordinate inside building", "Angle of observation", "MAC address of device", "Signal strength", "Number of milliseconds after 1/1/1970", "45 degree cutoff of orientation"),
  Data_Type = c("Time/Date", "Discrete", "Discrete", "Continuous", "Continuous", "Continuous", "Continuous", "Discrete"))
# Create the table using kable and kable_classic
kbl(data, caption = "Variable Description and Types") %>%
kable_classic(full_width = FALSE, html_font = "Cambria", font_size = 6)
```